### ISSUE TITLE
Tested it with different jsx language grammars. 

### ISSUE THREAD

**Issue by iamjacks** [timneutkens/language-styled-jsx#1]
It works with [atom-react](https://github.com/orktes/atom-react). However, it doesn't work with [language-javascript-jsx](https://github.com/subtleGradient/language-javascript-jsx) or [language-babel](https://github.com/gandm/language-babel). 

Update: I was able to get it to work with language-javascript-jsx by deleting `grammars/html with jsx textcontent.cson` in that package. The syntax highlighting for components from that package is a little bit better than atom-react IMO. 

Feedback: It might be a good idea to support <style> and not just <style jsx>. It's [recommended](https://github.com/zeit/next.js/wiki/Global-styles-and-layouts) for default/global styles and resets when using Next. 

Thanks for making this btw!

**Comment by timneutkens** [comment]
Thanks for this issue! I'll have a look into it sometime 👍

**Comment by ghost** [comment]
Can confirm it does not work with language-babel, which is the more popular package on Atom compared to the React one. Would be great if you could support it.

**Comment by timneutkens** [comment]
Deprecated this package in favor of https://github.com/zeit/styled-jsx#syntax-highlighting.
