### ISSUE TITLE
does not work when tag is on the same line

### ISSUE THREAD

**Issue by davibe** [timneutkens/language-styled-jsx#3]
A picture is worth 1000 words

<img width="305" alt="screenshot 2017-01-26 10 12 55" src="https://cloud.githubusercontent.com/assets/123929/22326069/898d21ae-e3b1-11e6-81ac-0c2385e23d02.png">

**Comment by timneutkens** [comment]
Deprecated this package in favor of https://github.com/zeit/styled-jsx#syntax-highlighting.
